### ISSUE TITLE
Installing River City Girls made all my other installs die..

### ISSUE THREAD

**Issue by Goretantath** [Huntereb/Awoo-Installer#100]
I installed River City Girls from sd and it works perfectly fine. I then decided i wanted to play a diff game and they all give me an error telling me to try opening it again..

**Comment by Masamune3210** [comment]
sounds like filesystem damage to me more than a issue with this app, as I use it all the time and have never had a issue like that

**Comment by Goretantath** [comment]
great.... i gotta find out who the fuk has a degausing ray pointed at my apt cause this is too repetetive of a problem with my stuff... 3ds and switch both eat micro sd cards like a person lost at sea for 2 months at a china inn buffet.

**Comment by impeeza** [comment]
Degausing?.
Hus is an excerpt from NSA security page:

"...unlike Hard Drives, degaussing SSD drives has absolutely no effect what so ever. So it would appear that there is no, single, fail safe way to guarantee that you can completely erase SSDs other than by physically destroying them..."

**Comment by Masamune3210** [comment]
All I can say is make sure your cards are legit and not take or low quality

**Comment by Huntereb** [comment]
Sorry about that. Make sure to keep backups, SD cards aren't exactly good at staying alive.
