### ISSUE TITLE
Problems installing freshly dumped XCI/NSP images from retail carts

### ISSUE THREAD

**Issue by SoftwareGuy** [Huntereb/Awoo-Installer#101]
Greetings,

I've just installed Awoo Installer v1.3.3 via downloading the latest version of the application from the releases section here and I'm having trouble installing XCI or NSPs of game cartridges that I've backed up using NXDumpTool.

However, when I go to install the said game (which was dumped to NSP format) onto either Internal NAND or MicroSD, the cute fox girl (her name escapes my mind atm) growls at me about Invalid Signature. I then select "Yes, I want a brick" or "Continue" (I forget the exact wording) and installation starts, but then she growls again and throws a "Failed to install GAME_NAME!" with an error code of...

```
OpenFileSystemWithId:122: Failed to open file system with id: @SdCardContent://registered/0000000D/<long hash>.nca. Error code: 0x00234c02
```

My switch EmuNAND is HOS 10.1, freshly created from the latest versions of Hekate, sept and Atomsphere. I decided to go with Awoo over Tinfoil as Tinfoil apparently doesn't like hekate and I don't feel like running a modded hekate to work around it.

I do have the signature patches installed as per the main menu. Help would be appreciated.

**Comment by crisftw** [comment]
You dont need a modded hekate to use Tinfoil. Just run the fusee-primary payload to use Tinfoil and thats it.

**Comment by Huntereb** [comment]
I'd grab your signature patches elsewhere, I keep being very behind updating them to work right here. This is indeed a signature patches issue, not an Awoo Installer issue.

**Comment by SoftwareGuy** [comment]
Thanks @Huntereb . I updated the sigpatches manually and Awoo happily installed the dumps without issue.

Thanks to the team for making a no-bullshit installer. We need more of these kinds of apps that just get the job done.

**Comment by stan9mai** [comment]
@SoftwareGuy I had the same problem, can you direct me to the correct version of sigpatches you installed? i tried over 10 versions and none of them worked, get the same error as you.

**Comment by lyling** [comment]
> 

how to update sigpatch manually?

**Comment by impeeza** [comment]
GO to GBATemp and other site of support.  by example, on https://gbatemp.net/threads/sigpatches-for-atmosphere-hekate-fss0-fusee-package3.571543/ there is a thread about sigpatches what they are and how you can update them.
