### ISSUE TITLE
[Feature Request] Use external resources (minimal theming)

### ISSUE THREAD

**Issue by Nazosan** [Huntereb/Awoo-Installer#104]
It occurred to me that it could be kind of nice if the resources were external instead of internal to the NRA.  Eg graphics, sounds, etc.  This would allow the user to replace them with their own.  Essentially resulting in a very minimal sort of theming.  I think this would keep things simple and minimal as seems to be the general aim for this software while still giving the user a little control (and also should be really easy for you to implement without having to put in a lot of time and effort.)  I would think that this could also reduce the NRO size a bit and allow a user to perhaps not have them at all (or at least some extra small blank fillers instead,) though I'll admit that if one is down to so little free space the amount this would save likely won't help very much.

**Comment by Huntereb** [comment]
We already support changing backgrounds and images, see https://github.com/Huntereb/Awoo-Installer/issues/9#issuecomment-554665196

**Comment by Nazosan** [comment]
Hmm.  Not quite the same, though it does do somewhat along these lines.  It doesn't give the user the base images to compare or even remove if they wanted and it also doesn't provide the sound effect.  This is a good start towards simple customization though, so I'll probably go ahead and use that myself.

**Comment by Huntereb** [comment]
Forgot to mention that "background.png" is also supported for replacing the background image.

**Comment by Huntereb** [comment]
Audio can now be customized as of https://github.com/Huntereb/Awoo-Installer/commit/b6fff2fe69d08ca6abcb5287635152db35c96eec .

**Comment by Nazosan** [comment]
Hey that sounds great.  Thanks.

**Comment by Huntereb** [comment]
Correct
