### ISSUE TITLE
Clean version

### ISSUE THREAD

**Issue by nv4** [Huntereb/Awoo-Installer#120]
Make a clean version without the weeb bullshit or post instructions on how to do so.
It's pretty sad when the only clean fork of this cancer is maintained by a wife-strangulating retard like blawar.

**Comment by HookedBehemoth** [comment]
You are always free to maintain your own fork of this.

We have no interest in doing that on this repository.

**Comment by Huntereb** [comment]
Cope

**Comment by CringeLord9001** [comment]
It's pretty sad that you're seething over cartoon boobies. Seethe some more idiot.

**Comment by citrus3301** [comment]
> Make a clean version without the weeb bullshit or post instructions on how to do so.
> It's pretty sad when the only clean fork of this cancer is maintained by a wife-strangulating retard like blawar.

Wow i'm so glad that we have a transphobic retard maintaining this fork instead of a wife strangulator, it's such a huge improvement.

**Comment by Masamune3210** [comment]
....what is the point of freaking whining about it. Either change it yourself or don't use it if you feel that strongly about it
