### ISSUE TITLE
HAHAHAHAH

### ISSUE THREAD

**Issue by citrus3301** [Huntereb/Awoo-Installer#121]
WHAT A FUCKING PUSSY LMAO
![wAGhJSsWveWzQAAAABJRU5ErkJggg](https://user-images.githubusercontent.com/57966199/102817832-7b739c00-439e-11eb-95a8-cf66a00b4ec8.png)
![3MSprK6trK79QaVHahEBRAARQAQQAUQAERBI4IebOAJzRZGIACKACCACiAAigAj8UALIxPmheJFyRAARQAQQAUQAEfjPEEAmznGO](https://user-images.githubusercontent.com/57966199/102817841-80385000-439e-11eb-912d-c0ec890d589f.png)

**Comment by Mystiko** [comment]
Hi blawar
