### ISSUE TITLE
Posted source code doesn't download sig patches

### ISSUE THREAD

**Issue by mrdude2478** [Huntereb/Awoo-Installer#122]
Posted source code in latest release compiles fine, but does not allow to download sig patches - even when supplying your own url for the patches.zip file.

**Comment by HookedBehemoth** [comment]
Source code or binary?

**Comment by mrdude2478** [comment]
> Source code or binary?

Built binary from current source code in the git, also the source code from the release page. The nro builds fine - and the default link in the config file works, however the nro running on the switch gives an error along the lines that the link is unreachable when trying to download the patches. The nro from the release page works fine though (which is weird).

**Comment by HookedBehemoth** [comment]
Did you corrupt your prodinfo?
If so you need to build with an older switch-curl version (<=7.69.1-1)

**Comment by mrdude2478** [comment]
> Did you corrupt your prodinfo?
> If so you need to build with an older switch-curl version (<=7.69.1-1)

No I never messed with prodinfo - I was using emunand to test on anyway. OK I will try downgrading curl as I am using the latest devkitpro files. Do you know how to downgrade that? I am pretty new to devkitpro and just used the tutorial from the wiki page to install, it put the latest files on automatically, then I updated it with dkp-pacman -Syu.
