### ISSUE TITLE
[Feature request 2 in 1] Option to mount XCI files after that renaming "Awoo-Installer" -> "Awoo"

### ISSUE THREAD

**Issue by iMonZ** [Huntereb/Awoo-Installer#134]
1. Implementing a feature for mounting XCI files like you see in the SXOS CFW.

2. after the first feature is added renaming this repo from "Awoo-Installer" -> "Awoo"

**Comment by eyeonus** [comment]
+1 to point 1

Don't really care about the renaming thing.

**Comment by HookedBehemoth** [comment]
1. out of scope
2. no
