### ISSUE TITLE
[Localization updated] Traditional Chinese langs for v1.3.4

### ISSUE THREAD

**Issue by qazrfv1234** [Huntereb/Awoo-Installer#135]
Hello,
the attachment for Awoo-Installer v1.3.4(the latest en.json )

[zh-rTW lang for Awoo v1.3.4.zip](https://github.com/Huntereb/Awoo-Installer/files/6027549/zh-rTW.lang.for.Awoo.v1.3.4.zip)

Many thanks,
Leo

**Comment by HookedBehemoth** [comment]
Thanks! Will be released in the next version.
https://github.com/Huntereb/Awoo-Installer/commit/664d9f3c6eff36c2669b1c69c994ddf82179186f
