### ISSUE TITLE
[Feature Request] Custom audio/visual elements (aka theming)

### ISSUE THREAD

**Issue by eyeonus** [Huntereb/Awoo-Installer#136]
So, currently the installer has the option to "Remove anime", but what I really want is the ability to change the background color, sounds, and images.

(Admittedly, personally, I'd only change the background color, although...
[this](https://www.pikpng.com/transpng/iohTTRT/) [wolf](https://i.pinimg.com/originals/44/63/2c/44632c5faf6d63e1e54ccb45280c2233.webp) [girl](https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/f/1d40ce2c-fedf-4f75-bff7-79faaafbd608/dbbh3hb-9f4ee4fb-6be8-49df-a76b-0f0b909fc102.png?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1cm46YXBwOiIsImlzcyI6InVybjphcHA6Iiwib2JqIjpbW3sicGF0aCI6IlwvZlwvMWQ0MGNlMmMtZmVkZi00Zjc1LWJmZjctNzlmYWFhZmJkNjA4XC9kYmJoM2hiLTlmNGVlNGZiLTZiZTgtNDlkZi1hNzZiLTBmMGI5MDlmYzEwMi5wbmcifV1dLCJhdWQiOlsidXJuOnNlcnZpY2U6ZmlsZS5kb3dubG9hZCJdfQ.YY7pUc-bhOHP7pucIxJMXSwXXI0aKE1d3CAwhBlvjOo)
and
[this](https://mcdn.wallpapersafari.com/medium/72/39/ZK8cOj.jpg) [fox](https://www.itl.cat/pngfile/big/296-2964366_anime-fox-girl-wallpaper-iphone.jpg) [girl](https://wallpapercave.com/wp/wp4014386.jpg)
are very cute.)

**Comment by HookedBehemoth** [comment]
You can load your own images from `/switch/Awoo-Installer/`
`background.png`, `awoo_inst.png` and `awoo_main.png`
