### ISSUE TITLE
NSP files with extremely long file name not listed

### ISSUE THREAD

**Issue by myeuropeanPAL** [Huntereb/Awoo-Installer#139]
NSP files with extremely long file names are not listed after choosing Install from SD card, for example:
Luigi’s Mansion 3 [Luigi’s Mansion 3 Multiplayer Pack 1][0100DCA0064A7001][US][v131072].nsp
or
Luigi’s Mansion 3 [Luigi’s Mansion 3 Multiplayer Pack 2][0100DCA0064A7002][US][v65536].nsp

**Comment by duckbill007** [comment]
It is not an awoo issue, but FS module limitations
