### ISSUE TITLE
About background.png

### ISSUE THREAD

**Issue by chronoss09** [Huntereb/Awoo-Installer#14]
Hi
It's good to make your own background but you must hide your anime in the new background to make this one better.

Like this for an exemple :
![2019120607140900-DA63280140B1530CD17755515D814CFE](https://user-images.githubusercontent.com/17669980/70300625-41b60e80-17f8-11ea-851c-4d3b85deb0eb.jpg)

**Comment by Huntereb** [comment]
In settings, you can disable those images by selecting "Remove anime". Those images can also be replaced. See: https://github.com/Huntereb/Awoo-Installer/releases/tag/1.1.0

**Comment by chronoss09** [comment]
ok thanks !!!
