### ISSUE TITLE
"Failed to retrieve HTTP header", but no request is ever made

### ISSUE THREAD

**Issue by psy-q** [Huntereb/Awoo-Installer#141]
On Atmosphère 0.18.1 via Hekate 5.5.4 (fuse-secondary), I can't use network installs in Awoo. 

With LAN installs, NS-USBloader 5.0 sees the Switch and submits the list of titles to install, but after selecting any of them, I get the error in the title. 

The same thing happens when using URL installs. I ran a web server in the local network and tried installing via URL pointing to it, but I can see in the logs that Awoo's HTTP request never arrives at the server. Using the "don't serve requests" feature and setting that web server in NS-USBLoader, the same error occurs. I've verified that other devices on the same wireless LAN as the Switch can retrieve files from the HTTP server.

USB installs mostly work, but as they are discouraged I wonder what I could do to get network installs to run.

**Comment by NonaSuomy** [comment]
Same issue with NS-USBloader 5.1.

**Comment by psy-q** [comment]
I'm not sure how it is related but some recent Atmosphère update (?) must have fixed it for me. At least on 0.20.1 it works fine.

**Comment by Mubexx** [comment]
Had Same Issue, Disabling My VPN Work For Me
