### ISSUE TITLE
failed to apply nosigchk

### ISSUE THREAD

**Issue by thib5** [Huntereb/Awoo-Installer#146]
Hi, Since I updated to switch OS 12.0.2 Athmospher 19.3 and Hekate 5.5.6 I have an error at boot that said : failed to apply nosigchk... 

It boot but none of my game work ... 

It's probably something stupid like I don't have the right patch or awoo is incompatible with this version however I can't find an answer on the web so I'm asking you guys !

Thanks

**Comment by impeeza** [comment]
please read the documentation on Hekate,  I am sure you didn't configure you «bootloader/hekate_ipl.ini» file with the `autonogc=1` directive or you are missing some Sigpatches.

**Comment by hxhieu** [comment]
@thib5 I ran into the same error but I was setting my NS a fresh Hetake/AMS. It was all fine until I used the Awoo (first time, fresh install) sigpatch feature.
Then I just copied the sigpatches back overwrite everything on the SC card and then it worked again so hope it'd help.

**Comment by firrae** [comment]
Awoo doesn't seem to download signatures that work for 12.1.0 either. I get the same error.

**Comment by Huntereb** [comment]
Awoo's signature patch installer is outdated and probably should be removed before the next release.
