### ISSUE TITLE
Titles will not load, "checking if software can be played".

### ISSUE THREAD

**Issue by takoyaki99** [Huntereb/Awoo-Installer#147]
I have the latest sigpatches, running hekate 5.5.6 and atmosphere 0.19.3.
No Nintendo account was on the system (had one before, but I system formatted)
The Nintendo account that used to be on it is on another system (it seems that the other system is designated as the secondary).
I used Awoo to install some of my game dumps, and some...other things,

To fix it, I'm re-dumping all NSPs, this time without console-specific into (using nx-dumptool), and then formatting my system.
I'll also try to go on the Nintendo website and see what's up with the accounts.
Additionally, I'll also try to go on the other Switch, delete the user, and then put the user on the system again, to see if that solves the problem for me.

**Comment by Huntereb** [comment]
You do not have the latest sig patches.
