### ISSUE TITLE
[Feature Request] Remove annoying "invalid NCA" messages

### ISSUE THREAD

**Issue by leonquest** [Huntereb/Awoo-Installer#148]
The app would be superb if you could fully automate large installations by having the options to remove ALL warning messages like "invalid NCA signature", etc.

**Comment by Masamune3210** [comment]
the errors are there for a reason, if you are installing something and it ends up with a invalid signature it's pretty important to tell the user

**Comment by leonquest** [comment]
> 
> 
> the errors are there for a reason, if you are installing something and it ends up with a invalid signature it's pretty important to tell the user

Having the option to turn them off wouldn't hurt anybody. Its 100% pure annoyance at this point.

**Comment by Masamune3210** [comment]
Just because you dont like the errors doesn't mean that they are useless.

**Comment by leonquest** [comment]
Just because you think users should be forced to press "ok" 300 times on a large installation doesn't mean its ok, or a even good UX.

**Comment by 16BitWonder** [comment]
Literally the 2nd checkbox in options is "Verify NCA signatures before installation".
Just untick that before your installations if you trust the files.

**Comment by leonquest** [comment]
The 2nd checkbox in options is "Verify NCA signatures before installation".
Just untick that before your installation if you trust the file(s).
