### ISSUE TITLE
Upload ns-usbloader

### ISSUE THREAD

**Issue by andrei-zgirvaci** [Huntereb/Awoo-Installer#149]
I am using ns-usbloader to install games from my pc. After I press upload from ns-usbloader and the installation is complete through awoo installer on my switch, does the NSP file gets cleaned after the installation or do I have to delete it manually?

**Comment by Masamune3210** [comment]
NSP never ends up on the switch, so no cleaning there. NSP on pc doesnt get deleted unless they changed something

**Comment by andrei-zgirvaci** [comment]
Thank you for the detailed explanation!
