### ISSUE TITLE
Applet mode alert even while pressing R

### ISSUE THREAD

**Issue by Entretoize** [Huntereb/Awoo-Installer#150]
I can only run Awoo Installer in applet mode, I tried to press and maintain R while launching Awoo but I still get the alert.

**Comment by masagrator** [comment]
You are wrong about how this work.
Applet mode is when you are going to hbmenu through album. So no matter what you do, if you run Awoo through album, it will be in applet mode.
Run any game while pressing R. You will run hbmenu in Application mode which you want.

**Comment by Entretoize** [comment]
`Run any game from dashboard while pressing R`
I read this sentence many times any I really don't understand games doesn't need hbmenu, so what ? I want to launch Awwo, not a game, but how to run it in non-applet mode ??

**Comment by masagrator** [comment]
> `Run any game from dashboard while pressing R`
> I read this sentence many times any I really don't understand games doesn't need hbmenu, so what ? I want to launch Awwo, not a game, but how to run it in non-applet mode ??

I have answered this question.
instead of trying you are doubting.
If you would try already, issue would be solved. But you try to be smart.

Just do it.

**Comment by Entretoize** [comment]
My daughter is playing now then I can't try but I think I understood. You mean I have to start a game with R and hbmenu will launch in non-applet mode. Sorry it's a translation issue (I'm french), I was understanding I have to press R to start any game in non-applet mode.

**Comment by Entretoize** [comment]
It works, thanks
