### ISSUE TITLE
new storage format support

### ISSUE THREAD

**Issue by impeeza** [Huntereb/Awoo-Installer#152]
Titles such as Lost in Random, Last Stop, and NMH3 cannot be installed properly due to the new storage format they have.

**Comment by whitezombie2000** [comment]
According to this it should be an easy fix for the dev. 

https://gbatemp.net/threads/sigpatches-for-atmosphere-hekate-fss0-fusee-package3.571543/page-70#post-9614339

**Comment by Huntereb** [comment]
This has been submitted in a PR and I'll accept it soon.
