### ISSUE TITLE
Fatal Freeze on FW 13.0 and Atmosphere 1.1.1

### ISSUE THREAD

**Issue by lajax01** [Huntereb/Awoo-Installer#154]
Just update my Switch, to FW 13.0 and Atmosphere 1.1.1.
Awoo is stop to work on the new fw.
Airplane mode, or not, the issue is the same. I can launch the app, made settings, access to all menu, but if I hit "Install from SD card", its froze up, then close the app, and drop back to main menu/dashboard.
Its just stop twerk.. 
Please make it work again.
This is my favorite app.

**Comment by monching14** [comment]
Happened to me as well. When i select Install from SD card.. it freezes.

**Comment by impeeza** [comment]
Don't hold your breath,. Look for alternatives like atmoxl, tinwoo or nsa installer

**Comment by lajax01** [comment]
Im sorry to hear this... :/ Its time to move on.
