### ISSUE TITLE
Apply Korean font

### ISSUE THREAD

**Issue by DDinghoya** [Huntereb/Awoo-Installer#159]
At once, Thank you for merging the Korean translation.

Tried testing Awoo built with help of "hippy dave" from GBATEMP as below; 

https://gbatemp.net/threads/can-you-help-me-build-awoo.604099/

There is no printing due to a problem with the font. Is there anything I can help to solve this problem? :)

**Comment by HookedBehemoth** [comment]
Will be released in the next version.

**Comment by DDinghoya** [comment]
> Will be released in the next version.

Thank you! Please don't forget it~ :)
