### ISSUE TITLE
AI: THE SOMNIUM FILES - nirvanA Initiative may not install correctly

### ISSUE THREAD

**Issue by Nazosan** [Huntereb/Awoo-Installer#173]
Apparently the new sequel to AI: THE SOMNIUM FILES, nirvanA Initiative (title ID 0100713016CCC000) does not install correctly via Awoo (or Goldleaf or most other installers apparently.)  According to the reports it can only be installed via DBI or Tinfoil (not quite sure which I trust least.)  This points to the game possibly doing something new that doesn't get along with most installers.  My speculation (and this is only speculation of course) is that it has something to do with the fact that it apparently does not work without its initial update (v65535) which, interestingly enough, is bigger than the actual game.  I'm suspecting a significant portion of the game is not actually properly installed with the actual installation and the update actually completes the installation and perhaps most installers don't integrate this properly.  It might be interesting to see what happens with installs from cartridges rather than digital, but I didn't find anything on the results from that yet (the game has only been out a few days and a lot of people had to reorder due to a lot of pre-order cancellations for unclear reasons.)

Interestingly, the result is that it produces the error "could not start software, please try again" and returns one to the home screen where the next attempt to run it offers to initiate a file check (which apparently will pass) -- this normally would imply an outdated set of sigpatches after a system update except it does this without an update and the sigpatches seem to have not changed in a while.  The currently available online sigpatch set apparently works with everything still and there is now a tool to automatically generate sigpatches for a specific firmware that seems to be working with the latest just fine too.  Given that it does apparently work when installed with DBI or Tinfoil without changing sigpatches and is doing it even without a system update, this would seem to imply it's just not that, despite the similar error.

Sorry I don't have more information on the specifics, but it seems worth looking into as future games might use whatever methodology causes problems here too if they think it's successful.

**Comment by johnkelvinliu** [comment]
big file on fat32 problem?

**Comment by HookedBehemoth** [comment]
should be fixed
