### ISSUE TITLE
Partially Installed Content Failed

### ISSUE THREAD

**Issue by ZHassanQ** [Huntereb/Awoo-Installer#174]
I am Using
FW 14.1.1
Atmosphere 1.3.1
Awoo-Installer

And I am Getting The Error And Telling Me That I Have Already Installed Content "Partially Installed Content ERROR" of Mario Party Superstars "The Game I Want To Install"

Updated Sig Patch To Latest From Awoo-Installer

**Comment by impeeza** [comment]
¿?

**Comment by ZHassanQ** [comment]
I am Using 
FW 14.1.1 
Atmosphere 1.3.1
Awoo-Installer

And I am Getting The Error And Telling Me That I Have Already Installed Content "Partially Installed Content ERROR" of Mario Party Superstars "The Game I Want To Install"

Updated Sig Patch To Latest From Awoo-Installer

**Comment by impeeza** [comment]
You need to ask on a support fourum like discord or GBATemp.  use DBI to remove unneeded content, Goldleaf have the same option.

**Comment by ZHassanQ** [comment]
What is DBI
And How Can I Use It On Goldleaf 10

**Comment by ZHassanQ** [comment]
I Don't See Any Option In Goldleaf Called DPI

Note: Goldleaf Version Is .10

**Comment by ZHassanQ** [comment]
> You need to ask on a support fourum like discord or GBATemp.  use DBI to remove unneeded content, Goldleaf have the same option.

Do You Mean DBI Installer In NSC-Builder

**Comment by Masamune3210** [comment]
DBI is a seperate homebrew, and yes it is the one referenced to in nscb. It has a clean orphaned files option that is useful for stuff like this

**Comment by ZHassanQ** [comment]
Will That Solve "Partially Installed Content"

**Comment by Masamune3210** [comment]
Yes, unless something else is wrong, that option should clean out any partial installs, any extra tickets for not installed applications, and a few other maintenance tasks like clearing out any pending system firmware updates

**Comment by ZHassanQ** [comment]
I Used DBI.nro To
"Clean Orphaned Files"
Then Install Over USB

And DBIbackend.exe In Computer To Choose My Game

And Now It Constantly Loading In Home Screen And When I Go To Goldleaf It Just The Title ID

Note: I Get Two Invalid Signatures In DBI

**Comment by ZHassanQ** [comment]
I Found The Solution 
Thx For Your Help 

Solution:: 

https://gbatemp.net/threads/corrupted-data-switch-sd-after-update.570527/
