### ISSUE TITLE
Errors while it tries to install games on latest version

### ISSUE THREAD

**Issue by Jack1Player** [Huntereb/Awoo-Installer#175]
I updated my CFW (Atmosphere) to latest version, as i do every new update. After the update, Awoo installer started to not install new games and, for some reasons, also the already installed games were not working.

I did again all the steps from zero, in order to install directly latest version of Atmo + AWOO, but the problem persisted.

As last chance, i tried to use TINFOIL. I installed a little game via Tinfoil (the same that i tried to install many time via Awoo) and it booted at first try. So i tried to start HB Menù with R on this game and, via Awoo, install another game but i get the same error.

I think, on latest Awoo on latest CFW based on latest Horizon OS, there is a problem of compatibility.

I can send you photos about the error i had.

Thank you for your work, i appreciate.

**Comment by Jack1Player** [comment]
EDIT 1: I tried many times to update sigpatches via different ways (Awoo installer, specific zips etc). It didn't work.

**Comment by impeeza** [comment]
Buddy. This is not a support site,. It's for big report. Please go to gbatemp or discord to get help. On gbatemp there are aain thraed about your problem and diagnose steps

**Comment by impeeza** [comment]
Detailed steps on: https://gbatemp.net/threads/firmware-and-nand-questions.612782/post-9835101

**Comment by Jack1Player** [comment]
> Detailed steps on: https://gbatemp.net/threads/firmware-and-nand-questions.612782/post-9835101

Thank you, but as i said, i solved my problem. In my opinion, it is a bug, with AWOO, on latest OS. I wasn't asking help, just report the problem

**Comment by johnkelvinliu** [comment]
Use dbi instead, although the dbi transferring speed shown is much slower, but it is very stable. Awoo often crash during installation and some even can not run after installation.

**Comment by HookedBehemoth** [comment]
should be fixed
