### ISSUE TITLE
how to disable applet mode 

### ISSUE THREAD

**Issue by Mohammedrida1010** [Huntereb/Awoo-Installer#177]
hello
how to get out of applet mode without game
i dont have any games in the switch and i cant enter tinfoil to install a game

**Comment by Masamune3210** [comment]
You need at least one launchable app that isn't a forwarder

**Comment by Mohammedrida1010** [comment]
can you give me any app name

**Comment by Masamune3210** [comment]
its quite literally any app that isnt a forwarder or a system title

**Comment by Mohammedrida1010** [comment]
idk any app im new

**Comment by johnny283** [comment]
If you can access internet and aren't banned then YouTube or something like that cuz it's free

**Comment by impeeza** [comment]
A)  This is not a support forum, please go to Discord or GBATemp.
B) use AtmoXL titel Installer (https://github.com/dezem/AtmoXL-Titel-Installer) and install any title.
