### ISSUE TITLE
Installing over USB

### ISSUE THREAD

**Issue by MegaPramuk** [Huntereb/Awoo-Installer#2]
Is there any reason that's not supported?
I mean, you can install locally, over the network and even the Internet but it's not possible to install over USB?

**Comment by Huntereb** [comment]
I welcome anyone to submit a PR implementing a USB installation method that:
- Is cross-compatible with different operating systems
- Doesn't require convoluted non-user-friendly host-side setup
- is free (libre) software
- Just werks

If I'm bored one day, I'll look into doing something like this. Would require me to learn a lot of new stuff.

**Comment by Huntereb** [comment]
We need testers for this feature. Join [my IRC](https://lewd.pics/irc/) and give me a shout if you wanna help out!

**Comment by Huntereb** [comment]
This feature has been implemented as of 1.3.0!
