### ISSUE TITLE
settings toggle to disable big titty momiji

### ISSUE THREAD

**Issue by notChocoMilk** [Huntereb/Awoo-Installer#200]
i don't like big titty momiji, it is very uncomfortable & makes me not want to use the software lol
(unless there is an option & i just didn't know because i haven't even installed it yet, kinda making me a dick)

**Comment by Masamune3210** [comment]
iirc there is an option to hide the character images. in fact, I'm almost sure there is, considering I do not like them either

**Comment by impeeza** [comment]
any of you are able to read?

if you search previous issues you will find:

https://github.com/Huntereb/Awoo-Installer/issues/14

please close the issue as duplicated.

**Comment by notChocoMilk** [comment]
closed, considering that i'm a retard
