### ISSUE TITLE
when installing over sd card, nsz files are not deleted after completion

### ISSUE THREAD

**Issue by Elionna** [Huntereb/Awoo-Installer#21]
When installing nszs already on the sd card, the game installs just fine, but when confirming to remove for cleanup, the nsz files still remain. NSP files are removed properly, this issue only occurs for nsz files.

**Comment by Huntereb** [comment]
Looks like @HookedBehemoth moved some stuff around in a previous commit. Easy fix, will be out with 1.3.0!

**Comment by Huntereb** [comment]
Fixed by https://github.com/Huntereb/Awoo-Installer/commit/e7c5f732431a6de50494266d9a892f92b81dc33c
