### ISSUE TITLE
USB/Net transfers never complete (macOS)

### ISSUE THREAD

**Issue by jooles** [Huntereb/Awoo-Installer#26]
hi there!

I only once managed to connect the NS to my MBP (USB C -> USB 2 cable plugged into an adapter) using latest version. However when I started transferring an nsz file via USB it keeps on loading. I see the file list already on the NS but when I click the filename the Awoo installer crashes.

Same is with Net install. I can connect to the NS and once I click "upload to NS" it keeps on loading without completing. When I then click the filename on the NS the app crashes.

Using latest Awoo, Atmosphere 0.10.1 with emuMMC.

Thanks for any help with this!

Cheers,
Jules

**Comment by Huntereb** [comment]
Have you tried on another machine that isn't running Mac OS?

**Comment by JulianHH** [comment]
tbh, not yet, will have the chance in either or 24hrs or the day after. Will report back then :)

Is there any way to get some logs for that possible Mac issue?

**Comment by Huntereb** [comment]
This would probably be a NS-USBloader issue. There's a log window you can view in the sidebar.

**Comment by JulianHH** [comment]
Okay, so it doesn't work on another Laptop (Windows 7) and I get the same behaviour.

The log shows this:

[ PASS ] NET: Your IP detected as: 0.0.0.0
[ PASS ] NET: Your port detected as: 6372
[ INFO ] 	Start chain
[ PASS ] NET: Initiation files list has been sent to NS.

So you'd recommand to post that issue within the NS-USBloader repo, right?
Thanks for your help though!

**Comment by developersu** [comment]
It's NS-USBloader issue
developersu/ns-usbloader#45
