### ISSUE TITLE
USB stack: Add reply 'EXIT' once user clicks 'Cancel' on the 'Select files' screen.

### ISSUE THREAD

**Issue by developersu** [Huntereb/Awoo-Installer#29]
**Steps to reproduce:**
1. Start Awoo using title-redirect mode
2. Click 'Install over USB'
3. Click 'Ok' on pop-up
4. Open NS-USBloader
    4.1 Select 500 NSP/NSZ files
    4.2 Click 'Upload to NS'
5. Click 'B' (Cancel)

**Expected results:**
NS-USBloader or any other PC-app receives 'EXIT' command:
_0x54 0x55  0x43 0x30 0x00 0x00 0x00 0x00_ [where first 4 bytes stands for ASCII's 'TUC0']

**Actual results:**
Nothing happens. 
User have to click 'Interrupt' by him-/herself on NS-UL. After that (is it the reason?) user can't transfer the same list again.

**Workaround:**
Reopen Awoo Installer. After reopen user can bypass the list of files again with no issues.

**Comment by Huntereb** [comment]
Fixed with https://github.com/Huntereb/Awoo-Installer/commit/e15331b7a1089c6ed879122a3b2c5d1a1052bfda .
