### ISSUE TITLE
Some NSZ files not being detected

### ISSUE THREAD

**Issue by Alkovalski** [Huntereb/Awoo-Installer#3]
I have some games here in the root of my SD card, bomberman and link's awakening, both .NSZ files, that are not being detected.....
I had Atelier Ryza too, and this one WAS found, so I don't know what's wrong
Could you help me? (also I'm not a native english speaker, so sorry for any misspelling :p)

**Comment by Huntereb** [comment]
Try renaming your extension from ".NSZ" to ".nsz". If this works, then it's an easy fix.

**Comment by Alkovalski** [comment]
Still no use....

![image](https://user-images.githubusercontent.com/57607487/68619990-529a8b00-04ab-11ea-9370-569ba65f1f5c.png)

![2019111117441400-DB1426D1DFD034027CECDE9C2DD914B8](https://user-images.githubusercontent.com/57607487/68620004-58906c00-04ab-11ea-9a8e-0d6c60ea2d42.jpg)

~here are screenshots, from the switch and the root of my sd card

**Comment by Huntereb** [comment]
Very odd. I'll try to recreate this soon.

**Comment by Alkovalski** [comment]
yeah, renaming to a short version fixed this issue, same happened in tinfoil when I was trying to install an XCI, when I've renamed the file, it worked

**Comment by Huntereb** [comment]
I can't seem to recreate this. I'm going to make it so case of the file extension no longer matters, but as your files are named they seem to show up on my device.

![](https://lewd.pics/p/L8Fk.jpg)

**Comment by 16BitWonder** [comment]
I think I ran into something similar to this issue, I couldn't get either:
- Luigi's Mansion 3 [0100DCA0064A6800][v65536].nsz
- Pokemon Let's Go, Eevee! [0100187003A36800][v131072].nsz
To be recognized in Awoo-Installer (or Goldleaf) until I removed the apostrophe (') from the file names. (Maybe unable to recognize that character?)

Not sure what the deal is with Bomberman though, all of those characters look fine to me.

**Comment by Huntereb** [comment]
I still can't recreate this, and I haven't changed anything significant that would fix this in recent commits. It not working in Goldleaf makes me think it might be a filesystem issue. Could you try restarting your device after copying files that don't work, or maybe running Hekate's "reset archive bit" option?

![](https://i.imgur.com/VfpfRl8.jpg)

**Comment by Alkovalski** [comment]
maybe it's something about my tinfoil installation, after changing to a shorter name like "luigi" or "bomberman", it worked, and as far as I've known, only me and my friend (whose switch I've "homebrewed") has this same problem

**Comment by Huntereb** [comment]
Are you using exfat?

**Comment by Alkovalski** [comment]
yep, exfat
now I'll try installing a NSZ of pokémon shield (renamed to just "shield.nsz"), if the installer dont work, I'll let you know

**Comment by 16BitWonder** [comment]
I figured out my issue, it wasn't anything to do with Awoo-Installer.
My files were using special ’ instead of the standard single quote '.

Replacing it with the regular ' made the files recognize in both Awoo and Goldleaf, sorry about that.

**Comment by Huntereb** [comment]
I will see if I can figure a way of making these characters work in file names.

**Comment by HookedBehemoth** [comment]
Closing due to a lack of reports and this not actually being about NSZ's.
A future update should resolve the apostrophe issue.

**Comment by Zixort** [comment]
I'm having the same issue right now with Awoo Installer 1.3.4, Hekate 5.5.4 and Atmosphere 0.18.0, with mesosphere, in the emuMMC.

The filenames are:
Pokémon Shield[01008DB008C2C000][US][v0].nsz
Pokémon Shield[01008DB008C2C800][US][v393216].nsz

They won't appear in the Awoo Installer menu, however I can see them on the PC. Changing the name from "Pokémon" to "Pokemon" resolved the issue. Seems to have something to do with caracters.

**Comment by HookedBehemoth** [comment]
Nintendo's FAT filesystem implementation mishandles Unicode characters. There is no way of accessing that file because of that.

There probably won't be a fix for that until Atmosphère reimplements that and addresses that issue ([planed for 2021-2022 as of today](https://github.com/Atmosphere-NX/Atmosphere/blob/master/docs/roadmap.md#fs-reimplementation)).
