### ISSUE TITLE
Building instructions?

### ISSUE THREAD

**Issue by furanzoni** [Huntereb/Awoo-Installer#35]
How can I build this (so get the .nro file) myself? I'm on Arch Linux, have libnx-git and devkita64.

**Comment by ELY3M** [comment]
you need to get zstd.

**Comment by furanzoni** [comment]
@ELY3M I have it.

**Comment by furanzoni** [comment]
How to build?

**Comment by ELY3M** [comment]
I just type make

**Comment by furanzoni** [comment]
Forked the repo. Typing make gives me this:
```
#comment this out if you are hacking on the code or compilation will take forever
make --no-print-directory -C include/Plutonium -f Makefile lib
make[1]: Makefile: No such file or directory
make[1]: ***  No rule to make "Makefile".  Stop.
make: *** [Makefile:170: build] Error 2
```

**Comment by furanzoni** [comment]
`sudo make` gives me this instead:
`Makefile:6: *** "Please set DEVKITPRO in your environment. export DEVKITPRO=<path to>/devkitpro".  Stop.`
Although I've already set DEVKITPRO in my environment.

**Comment by andres242242** [comment]
amigos creadores de esta exelente herramienta me encanta me parese mil veses mejor que tinfoil que es una mierda amigos una pregunta el dia de ayer estaba instalando los juegos mediante htpps y drive y funciono pero hay ya no me deja por google y tambien tendo no importa que enlace siemre da herror al descargar y estoy desde el menú de inicio completo el anexo imagen del problema que esta presentando http://tiny.cc/nz4njz

**Comment by furanzoni** [comment]
> amigos creadores de esta exelente herramienta me encanta me parese mil veses mejor que tinfoil que es una mierda amigos una pregunta el dia de ayer estaba instalando los juegos mediante htpps y drive y funciono pero hay ya no me deja por google y tambien tendo no importa que enlace siemre da herror al descargar y estoy desde el menú de inicio completo el anexo imagen del problema que esta presentando http://tiny.cc/nz4njz

1. I don't think Spanish is a supported language? Please write in English, even Google Translate should be more than good 
2. Make a new issue, this is another matter
