### ISSUE TITLE
error when trying to download games from drive or from any website like dropbox

### ISSUE THREAD

**Issue by andres242242** [Huntereb/Awoo-Installer#36]
There is an error in the downloads of the web if I enter by google and write in id of the download file it gives the photo terror as if I download it from dropbox

https://www.dropbox.com/s/qcmgewsu7wjt2gc/IMG_20200206_075316.jpg?dl=0

**Comment by Huntereb** [comment]
Make sure the file is public and that you see the name of the file before attempting to install. I really need to make it check for a 404 rather than page title. Oops!
