### ISSUE TITLE
Error curl.h

### ISSUE THREAD

**Issue by Le0T** [Huntereb/Awoo-Installer#4]
Hi there, when I try to build it with "make" it throws me an error about curl.h:

`leot@leot:~/Scaricati/Awoo-Installer$` make
make --no-print-directory -C include/Plutonium -f Makefile lib-switch
make[4]: '/home/leot/Scaricati/Awoo-Installer/include/Plutonium/Plutonium/Output-switch/lib/libpu.a' is up to date.
netInstall.cpp
aarch64-none-elf-g++ -MMD -MP -MF /home/leot/Scaricati/Awoo-Installer/build/netInstall.d -g -Wall -O2 -ffunction-sections -march=armv8-a+crc+crypto -mtune=cortex-a57 -mtp=soft -fPIE  -I/home/leot/Scaricati/Awoo-Installer/include -I/home/leot/Scaricati/Awoo-Installer/include/ui -I/home/leot/Scaricati/Awoo-Installer/include/data -I/home/leot/Scaricati/Awoo-Installer/include/install -I/home/leot/Scaricati/Awoo-Installer/include/nx -I/home/leot/Scaricati/Awoo-Installer/include/nx/ipc -I/home/leot/Scaricati/Awoo-Installer/include/util -I/home/leot/Scaricati/Awoo-Installer/include/Plutonium/Plutonium/Output-switch/include -I/opt/devkitpro/portlibs/switch/include -I/opt/devkitpro/libnx/include -I/home/leot/Scaricati/Awoo-Installer/include/Plutonium/Plutonium/Output-switch/include -I/home/leot/Scaricati/Awoo-Installer/build -D__SWITCH__ -D__DEBUG__ -DNXLINK_DEBUG -fno-rtti -std=gnu++17 -c /home/leot/Scaricati/Awoo-Installer/source/netInstall.cpp -o netInstall.o 
/home/leot/Scaricati/Awoo-Installer/source/netInstall.cpp:30:10: fatal error: curl/curl.h: No such file or directory
 #include <curl/curl.h>
          ^~~~~~~~~~~~~
compilation terminated.
make[1]: *** [/opt/devkitpro/devkitA64/base_rules:14: netInstall.o] Error 1
make: *** [Makefile:169: build] Error 2
leot@leot:~/Scaricati/Awoo-Installer$ nano Makefile`

I already installed libcurl-dev but no luck.
Any Help? Thanks!

**Comment by Huntereb** [comment]
Install switch-libcurl.
