### ISSUE TITLE
Chines Translate files ,here

### ISSUE THREAD

**Issue by kavid** [Huntereb/Awoo-Installer#40]
Chines Translate files ,here
pls, upload your in the project
n
[zh_cn.zip](https://github.com/Huntereb/Awoo-Installer/files/4196535/zh_cn.zip)

**Comment by Huntereb** [comment]
This is a tougher one... The way we handle fonts currently makes implementation of Chinese languages a bit harder than any others. We'd have to load that character set as well. I'll mark this as an enhancement and look into it some day. Thank you for the contribution!

**Comment by Polytoo** [comment]
hi guys,
l didn't notice this issue until I have done the whole things. 
[#56 ](https://github.com/Huntereb/Awoo-Installer/pull/56)

**Comment by HookedBehemoth** [comment]
I'm sorry for letting your work go to waste.
We've accepted a pull request that addressed this.

I hope you don't get discouraged from contributing to this or other open source projects in the future.
