### ISSUE TITLE
Wrong LAN IP

### ISSUE THREAD

**Issue by scalp42** [Huntereb/Awoo-Installer#5]
hi @Huntereb,

When trying to install over LAN, it's showing a `10.143.138.62` but local network is `192.168.128.xx`:

```
$:/tmp
> localip
192.168.128.42

$:/tmp
> ping 10.143.138.62
PING 10.143.138.62 (10.143.138.62): 56 data bytes
Request timeout for icmp_seq 0
Request timeout for icmp_seq 1
Request timeout for icmp_seq 2
^C
```

I tried to enter the IP in NS-USBloader but no luck either.

Any ideas?

**Comment by Huntereb** [comment]
I assume this was resolved? Let me know if this is a recurring issue.
