### ISSUE TITLE
nsz installation crashed in 9.2

### ISSUE THREAD

**Issue by k1988** [Huntereb/Awoo-Installer#52]
i upgraded my switch's system to v9.2. but the system is crashed when installing nsz files。

ns-usbloader-2.1.jar
Awoo-Installer-1.3.2.nro
Installed over usb.

**Comment by Huntereb** [comment]
Try installing them over LAN or the internet. USB tends to have issues on varying machines.

**Comment by k1988** [comment]
emm,i tried with tinfoil v8.1 over usbfs, everything were fine. 
ps : tinfoil v8.0 had a empty list over usbfs.

i will try with Awoo-Installer over lan later

**Comment by deadair3210** [comment]
9.2 installations work fine for me, make sure your files are not damaged in any way, and try either network or putting the files on the SD card

**Comment by Polytoo** [comment]
Tinfoil v8.0 or above version need a new usb driver installed, however this driver will cause Awoo installer USB problem.
Another known issue that Awoo installer doesn't work with USB3.1 gen2 protocol, if you can't install over USB, just try another non-USB3.1 port, it maybe working well.

**Comment by Huntereb** [comment]
Going to close this since it just looks like user-error.
