### ISSUE TITLE
Installed Updates Are Not Merging With Prior Updates

### ISSUE THREAD

**Issue by 16BitWonder** [Huntereb/Awoo-Installer#53]
I noticed that when installing updates with Awoo, previous updates are still listed (and using space) in other homebrew like Goldleaf.
Whereas other installers after installing don't list prior updates, is this issue happening on any other units or is there something wrong with my setup?

Steps to reproduce:
- Install title X
- Install update 1 for title X
- Install update 2 for title X
	
Check listed updates and find that both update 1 and 2 are listed rather than just 2.
(And that space is being used for both updates, e.g. if update 1 is 30MB and update 2 is 32MB, 62MB is used instead of 32MB)
	
I tested with Deltarune Chapter 1 and posted the results below.
Note: All installations were done over USB.

=================================
Awoo Setup:
Atmosphere v0.10.4
HOS: 9.0.1
Installer: Awoo-Installer v1.3.2
PC Client: NS-USBLoader v2.1
Format Installed: NSP/NSZ (Happens for both formats)
\=================================

Deltarune Update 1 (v65536):  31.04MB
Deltarune Update 2 (v262144): 31.72MB

The sizes listed below are the used space of my SD card as the contents are installed.

Base:        304,974.406MB

Update 1: 305,005.687MB
Diff:     +31.28MB

Update 2: 305,037.656MB
Diff:     +31.97MB

After installing both, they are both present when viewing the title's contents in Goldleaf:
https://i.imgur.com/0d4yTbi.jpg

*After deleting update 1, and keeping update 2
Update 2: 305,006.375MB
Diff:     -31.28MB

===================
Goldleaf Setup:
Atmosphere v0.10.4
HOS: 9.0.1
Installer: Goldleaf v0.8
PC Client: NS-USBLoader v2.1
Format Installed: NSP
\===================

Deltarune Update 1 (v65536):  31.04MB
Deltarune Update 2 (v262144): 31.72MB

Base:    304,974.406MB

The sizes listed below are the used space of my SD card as the contents are installed.

Update 1: 305,005.687MB
Diff:     +31.28MB

Update 2: 305,006.375MB
Diff:     +0.68MB

After installing both, only update 2 is present when viewing the title's contents in Goldleaf:
https://i.imgur.com/jAWwt5N.jpg

*Only update 2 displaying as installed now, and correct SD space is used

**Comment by deadair3210** [comment]
make sure that the updates you are trying to use don't have the delta fragments stripped out. without them the update is just applied fullsale which would look like what you are seeing

**Comment by 16BitWonder** [comment]
Forgive the dumb question: is there some way of checking for stripped delta fragments outside of having the hash of the original nsp?
I got the two updates listed above from a new source and verified the hashes of each nca and the issue was still present, though I wouldn't know if the deltas were stripped or not.

**Comment by deadair3210** [comment]
If the same nsp is showing differences between the different installers, then it's not a issue with Delta's I don't think

**Comment by HookedBehemoth** [comment]
Thanks for pulling our attention towards this.
Will fix.

**Comment by Huntereb** [comment]
I believe we erase existing content before installations now? That was a recent edition. Usually this is a non-issue since update data "should" contain all previous updates if packaged properly.

**Comment by Huntereb** [comment]
This should be fixed as of https://github.com/Huntereb/Awoo-Installer/commit/0c929ca357c57ffa470e49aeccecf26153c4b3dc .

**Comment by 16BitWonder** [comment]
Tested 0c929ca with Deltarune again. 
Installing both updates with it does not have both updates showing up in Goldleaf anymore.
However, going by my SD's used space I jotted down while testing it seems like the space is still being taken up by both the current and previous update.

Base: 380,938,223,616 bytes
Installed Update 1: 380,971,024,384 bytes    |    Diff from Base: +32,800,768 bytes
Installed Update 2: 381,004,546,048 bytes    |    Diff from Base: +66,322,432 bytes

=Completely uninstalled title and reinstalled=
Base: 380,938,223,616 bytes
Installed Update 2: 380,971,745,280 bytes    |    Diff from Base: +33,521,664 bytes

**Comment by Huntereb** [comment]
Not sure if Goldleaf should even be listing more than one update, they should merge naturally and the latest update NSP, and reference previously installed NCAs. If the latest update NCA *doesn't* contain all update data, I would consider that an improperly made update NSP.

**Comment by 16BitWonder** [comment]
> Not sure if Goldleaf should even be listing more than one update

It shouldn't, but with older Awoo it would consistently list more than one if I installed a newer version https://i.imgur.com/0d4yTbi.jpg.

0c929ca Seems to have fixed that from my quick test with Deltarune but it looks like the issue of space being taken up by both the 1st and 2nd update is still there.
Rather than just the space of the 2nd update being used.

I'll test with a few more titles later to make sure Deltarune isn't just some weird edge-case I ran into.

**Comment by Huntereb** [comment]
This at least will stop people from complaining lol... We'd have to do some comparison of what contents are installed and what aren't and remove the ones that don't exist in the latest update if this were to genuinely be fixed. As of right now this is exactly how tinfoil handles it. I implemented deleting previous contents for this exact reason, and I never download updates so I never checked this (I just get them off the home menu).

**Comment by 16BitWonder** [comment]
After running some additional tests, it looks like this issue is completely solved with a FULL reboot after installing updates.
I noticed half-way through my tests that, installing a new version of an update and checking Goldleaf BEFORE rebooting would display both update 1 and the newly installed update 2.

When I then used reboot-2-payload to jump into Hekate to check my SD space it said that the space of both updates was being used.
However, after fully rebooting into Atmosphere and checking Goldleaf, only the newest update is listed and checking used space with nxmtp or Hekate would then show that only the most recent update was present and the old update was no longer taking up any additional space.


## Mario Odyssey
```
Base: 380,574,072,832 bytes
Installed Update 1: 380,866,920,448 bytes | Diff from Base: + 292,847,616 bytes
Installed Update 2: 381,264,625,664 bytes | Diff from Base: + 690,552,832 bytes

BEFORE REBOOT, update 1 & 2 listed in Goldleaf
AFTER REBOOT, only update 2 listed: 380,971,614,208 bytes | Diff from Base: + 397,541,376 bytes

=Completely uninstalled title and reinstalled=
Base: 380,574,072,832 bytes
Installed Update 2: 380,971,778,048 bytes | Diff from Base: + 397,705,216 bytes
AFTER REBOOT      : 380,971,614,208 bytes | Diff from Base: + 397,541,376 bytes
```

## Cuphead
```
Base: 380,893,691,904 bytes
Installed Update 1: 380,971,745,280 bytes | Diff from Base: + 78,053,376 bytes
Installed Update 2: 381,049,798,656 bytes | Diff from Base: + 156,106,752 bytes

BEFORE REBOOT, update 1 & 2 listed in Goldleaf
AFTER REBOOT, only update 2 listed: 380,971,614,208 bytes | Diff from Base: + 77,922,304 bytes

=Completely uninstalled title and reinstalled=
Base: 380,893,691,904 bytes
Installed Update 2: 380,971,876,352 bytes | Diff from Base: + 78,184,448 bytes
AFTER REBOOT      : 380,971,614,208 bytes | Diff from Base: + 77,922,304 bytes
```


I went back and did the same tests with Deltarune, doing a full reboot after installing the latest update and can confirm that neither double-listed updates in Goldleaf or space being used by the old update are present.


## Deltarune
```
Base: 380,938,092,544 bytes
Installed Update 1: 380,971,024,384 bytes | Diff from Base: + 32,931,840 bytes
Installed Update 2: 381,004,677,120 bytes | Diff from Base: + 66,584,576 bytes

BEFORE REBOOT, update 1 & 2 listed in Goldleaf
AFTER REBOOT, only update 2 listed: 380,971,614,208 bytes | Diff from Base: + 33,521,664 bytes

=Completely uninstalled title and reinstalled=
Base: 380,938,092,544 bytes
Installed Update 2: 380,971,745,280 bytes | Diff from Base: + 33,652,736 bytes
AFTER REBOOT      : 380,971,614,208 bytes | Diff from Base: + 33,521,664 bytes
```
