### ISSUE TITLE
Install from lan-wifi is very slow. 

### ISSUE THREAD

**Issue by Polytoo** [Huntereb/Awoo-Installer#55]
I put my NSZ NSP files into my web dir on my windows 10, then I install them from wifi.
But the speed just around 5M/s to 7M/s ...

Is it a driver problem? 
or we can modify the code to improve the install speed?

**Comment by HookedBehemoth** [comment]
Those speeds fit our experience with the switch's wifi speeds.
Recommendations are the usual. Use a 5GHz wifi access point and slightly increase the MTU in your wifi profile.

**Comment by Entretoize** [comment]
> I put my NSZ NSP files into my web dir on my windows 10, then I install them from wifi.
> But the speed just around 5M/s to 7M/s ...
> 
> Is it a driver problem?
> or we can modify the code to improve the install speed?

5M/s ?! I'm at 0.2M/s :-(

**Comment by johnkelvinliu** [comment]
use a usb 3.0+ type c usb cable would help.
But do not use awoo, using DBI is much more stable.
