### ISSUE TITLE
Why not put an .nsp to the release?

### ISSUE THREAD

**Issue by rekcah1986** [Huntereb/Awoo-Installer#58]
It will be more convenient.

**Comment by HookedBehemoth** [comment]
I personally don't see the appeal of homebrew NSP's anymore as title override is a feature in every major CFW for a very long time.
Our own stance and the warnings in the application would also make it seem hypocritical to allow our own garbage NCA's and warn of others.

**Comment by rekcah1986** [comment]
Oh, I see, but is there any other way to solve the problem of "applet mode"?

**Comment by HookedBehemoth** [comment]
Hold down R while launching a game. This will launch hbloader in the application memory pool.
