### ISSUE TITLE
How come the make keep rebuilding every files?

### ISSUE THREAD

**Issue by Polytoo** [Huntereb/Awoo-Installer#59]
I don't change anything in the Awoo-Installer dir after a complete success build, but when I type 'make' command again, it rebuild everything ...

**Comment by HookedBehemoth** [comment]
Comment out the line in the make file where it builds plutonium.
There is a line above that telling you about that.

**Comment by HookedBehemoth** [comment]
Because plutonium's library gets touched by that and your compiler considers all the awoo UI code as invalidated so it will rebuild all that.

**Comment by Polytoo** [comment]
OK, I found it.
Now, it become fast~

Thank you~ @HookedBehemoth

**Comment by HookedBehemoth** [comment]
Great :+1:
