### ISSUE TITLE
Error zstd.h

### ISSUE THREAD

**Issue by Le0T** [Huntereb/Awoo-Installer#6]
Hello again, i got another error while compiling:

aarch64-none-elf-g++ -MMD -MP -MF /home/leot/Scaricati/Awoo-Installer/build/nca_writer.d -g -Wall -O2 -ffunction-sections -march=armv8-a+crc+crypto -mtune=cortex-a57 -mtp=soft -fPIE  -I/home/leot/Scaricati/Awoo-Installer/include -I/home/leot/Scaricati/Awoo-Installer/include/ui -I/home/leot/Scaricati/Awoo-Installer/include/data -I/home/leot/Scaricati/Awoo-Installer/include/install -I/home/leot/Scaricati/Awoo-Installer/include/nx -I/home/leot/Scaricati/Awoo-Installer/include/nx/ipc -I/home/leot/Scaricati/Awoo-Installer/include/util -I/home/leot/Scaricati/Awoo-Installer/include/Plutonium/Plutonium/Output-switch/include -I/opt/devkitpro/portlibs/switch/include -I/opt/devkitpro/libnx/include -I/home/leot/Scaricati/Awoo-Installer/include/Plutonium/Plutonium/Output-switch/include -I/home/leot/Scaricati/Awoo-Installer/build -D__SWITCH__ -D__DEBUG__ -DNXLINK_DEBUG -fno-rtti -std=gnu++17 -c /home/leot/Scaricati/Awoo-Installer/source/nx/nca_writer.cpp -o nca_writer.o 
/home/leot/Scaricati/Awoo-Installer/source/nx/nca_writer.cpp:24:10: fatal error: zstd.h: No such file or directory
 #include <zstd.h>
          ^~~~~~~~
compilation terminated.
make[1]: *** [/opt/devkitpro/devkitA64/base_rules:14: nca_writer.o] Error 1
make[1]: *** Waiting for unfinished jobs....
make: *** [Makefile:169: build] Error 2

I already installed switch-zlib package. What am I missing this time?
Thank you again!

**Comment by Huntereb** [comment]
zstdlib hasn't been added to the devkitpro repository yet. You'll have to compile and install it manually from [here](https://github.com/devkitPro/pacman-packages/pull/117).
