### ISSUE TITLE
Support/Syntax for Split XCI installs from SD card?

### ISSUE THREAD

**Issue by YukinoAi** [Huntereb/Awoo-Installer#69]
Split XCI files do not seem to install from SD card, even with the archive flag.  Split NSP install normally.

During testing, compressing one XCI to "XCZ" (XCI with compressed NCA) to where it was under 4 GB made it installs normally, so it is not an issue with the file persay, but either the syntax or the program.

Ideally it should work from folders with the archive flag that have been structured like this:

Folder structure 1:
Create "folder.xci"
folder.xc0
folder.xc1
folder.xc2

Folder structure 2:
Create "folder.xci"
00
01
02

Either one of the above would be sufficient, but supporting both syntaxes would be ideal. Or if this feature is not supported, could it be removed from the list of supported features on the main page?

Versions used: Awoo v1.3.2 on OFW 10.0.1 and ATM 12.0

**Comment by Huntereb** [comment]
You'll have to use fat32's archiving flag. More info can be found [here](https://gbatemp.net/threads/legal-nsp-splitter-for-fat32.520213/).

**Comment by YukinoAi** [comment]
Why was this closed? Please actually read my first post. 

I did try to use the archive flag on both of the folder structures specified and using the archive flag on a Fat32 does NOT fix the issue.

It DOES fix the issue for split .NSP installs but not for split .XCI installs so this is not a user-error but a different problem.

**Comment by ablebest** [comment]
This really shouldn't be closed, I'm having the exact same problem

**Comment by protivakid** [comment]
This is still an issue for me as well. Awoo Installer won't even open the directory if all that's in there is a folder, ending in .xci, with archive set. It simply bounces back to the main Awoo menu.

**Comment by HeadsarmCode** [comment]
Still an issue in 1.3.6
