### ISSUE TITLE
What's this garbage?

### ISSUE THREAD

**Issue by ZeroGravity83** [Huntereb/Awoo-Installer#7]
![a](https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQhAy1RHatkpABmFHLfT0veFx8oPunUaCKfr5GYbA5NnOgAgCLpmA&s)

Hating TX is one thing, but you don't even allow people to use this if they have SX OS? Are you retarded? How much of a self-righteous piece of shit can you be?
Toxic kids like you are cancer to the community. Delete this crap and go kill yourself, you worthless disgusting furry shit. Nobody is going to use your garbage homebrew. Nobody wants you alive.

**Comment by HookedBehemoth** [comment]
rude!
