### ISSUE TITLE
Unstable speed between 0.00MB/s and 40-50MB/s microSD

### ISSUE THREAD

**Issue by pitrako** [Huntereb/Awoo-Installer#72]
I get something like 0-8-15-35-40-50MB/s speed after a while in the process of installing on a microSD, at the beginning It starts the installation between 35-40-50MB/s.

**Comment by masagrator** [comment]
If you have this only in NSZ, then this is normal.

**Comment by pitrako** [comment]
I tried NSP, It doesn't reach 0.00MB/s now but 8.38MB/s It's the minimum and 41.94MB/s the maximum yet.

**Comment by deadair3210** [comment]
NSP files and the like are containers. The NCA files and others have to be moved out of the containers into the correct spot, and registered as installed to the system. Going up and down in speed is normal for the most part, as bigger files will copy faster since it's not switching away to do something else all the time

**Comment by Huntereb** [comment]
This is just due to how we poll for speeds during installations. We do it less so that we don't have to update the UI as often. The code could probably be made to display the actual speed a little more accurately, though.

**Comment by duckbill007** [comment]
What can be more accurate than transferred bytes divided by elapsed time from start?

**Comment by johnkelvinliu** [comment]
what microsd are you using to get 50MB/s writing speed? USB3.0+ cable installation? 
Laxar PLAY & Sandisk ultra 1TB microSD card can only get max about 33MB/s (wave) write with USB 2.0 cable installation; while it is max about 38MB/s write (wave) with 1G LAN installation.

**Comment by HookedBehemoth** [comment]
code sucks too much to fix this
