### ISSUE TITLE
Failed to install .nsp on Mac OS

### ISSUE THREAD

**Issue by WavyDers** [Huntereb/Awoo-Installer#73]
I am trying to install my .nsp files on my mac over my local network because I cannot get NS-USBloader to detect my switch through USB but I ran into the following error.

PerformRequest:93: Failed to retrieve HTTP Header: Couldn't connect to server. 

I am on MacOS 10.14.6, Awoo Installer v1.3.2, and NS-USBloader v2.2.

**Comment by Huntereb** [comment]
This is likely a PC-side issue. You might be best asking for help at [ns-usbloader](https://github.com/developersu/ns-usbloader)'s git page.
