### ISSUE TITLE
sigpatches are outdated 

### ISSUE THREAD

**Issue by Ali-Asim800** [Huntereb/Awoo-Installer#75]
the sigpatches option is outdated and should either be removed or updated frequently to prevent somebody  thinking it's updated and getting their stuff corrupted. needs to be fixed.

**Comment by Huntereb** [comment]
I'll get this fixed today, sorry! Been busy!

**Comment by Huntereb** [comment]
Updated. "Should" work with Hekate + Atmosphere.

**Comment by Ali-Asim800** [comment]
Good. Thanks I knew you would update the sigpatches. Keep up the good work huntereb! I'm looking forward to new updates!

**Comment by Borrajo** [comment]
The "manage signature patches" option does not work for me, it always says that it cannot find the file. I am obviously connected to the internet. I created a local server with patches.zip file and there is no outgoing http request from awoo.

**Comment by HookedBehemoth** [comment]
Current release is broken on incognito'd switches. Will fix.

**Comment by Borrajo** [comment]
thanks! i test with applied only 90dns, without incognito and works! 
![photo_2020-06-01_19-58-44](https://user-images.githubusercontent.com/8571788/83463206-b8e4fc00-a443-11ea-914a-31497ec5e412.jpg)
