### ISSUE TITLE
Installed game via usb deleted after reboot

### ISSUE THREAD

**Issue by brokentechnology** [Huntereb/Awoo-Installer#76]
So unsure exactly what is causing this, it may not be Awoo-Installer at all. I am hitting an issue where an installed game via usb connection is deleted after I reboot the console. Here is my example:

- 64GB is free.
- Install Xenoblade.
- 50GB is free (as expected, since game is 14GB).
- Reboot the system.
- 50GB is free. Game needs to be reinstalled.

Now I am aware the game will not show up when booted into sysnand, but that is not the problem. Per my example, it is deleted. It's as if installing via USB is creating a temporary copy. Am I skipping a step, or have I hit some weird bug. 

Here is my config:

- Atmosphere: 10.x 
- System firmware: 10.0.3
- Latest Awoo-Installer and sigpatches
- Booting into fusee-primary from hekate

Additionally, if it matters, the game is XCI format, and I am using tinfoil with XCI option checked. Installing produces no errors.

**Comment by Huntereb** [comment]
The game starts fine until a reboot? I'd try another SD card, or install to internal storage and see if the problem persists.

**Comment by brokentechnology** [comment]
> The game starts fine until a reboot? I'd try another SD card, or install to internal storage and see if the problem persists.

Correct, game works flawlessly. No freezing, or anything. I'll test internal and see if it happens.

**Comment by brokentechnology** [comment]
Internal storage worked fine. Question: I setup my Switch CFW to point to the /Nintendo folder, so my digital and physical games could be accessed without having to duplicate my entire folder (which is 144GB~). Is this causing the deletion issue potentially?

**Comment by Huntereb** [comment]
You mean emummc is reading from the same folder as sysmmc? I've never used emummc, I'm not really sure. It's possible.

I'd try the same setup on another SD card if possible and see if it still does it. If you can't do that then maybe try configuring things differently.
