### ISSUE TITLE
No

### ISSUE THREAD

**Issue by skyclanforlife** [Huntereb/Awoo-Installer#77]
[Edit: kek]

**Comment by deadair3210** [comment]
don't you have something better to do than spam at people...

**Comment by BlancBestGirl** [comment]
> don't you have something better to do than spam at people...

He literally doesn't. He's on a discord server im in, it's kinda sad how stupid he is

**Comment by deadair3210** [comment]
That's depressing. GitHub really needs antispam tools to get rid of this. Spam fests have been happening a lot lately
