### ISSUE TITLE
(new feature) Compatibility with split nsp/xci files

### ISSUE THREAD

**Issue by Ali-Asim800** [Huntereb/Awoo-Installer#79]
It would be great if awoo could support split nsp/xci files. I know you can use nsz/xcz but it would be even better if there was support for split files. For some reason they're detected in Tinfoil but not goldleaf or awoo, would appreciate if at least this feature could come to life.

**Comment by Huntereb** [comment]
This is already a feature thanks to fat32's archive flag. See: https://github.com/Huntereb/Awoo-Installer/issues/69#issuecomment-623235234
