### ISSUE TITLE
XCI format

### ISSUE THREAD

**Issue by chronoss09** [Huntereb/Awoo-Installer#8]
Hi !

I like your new installer and i want to ask u, can u add installation of xci file ?

Thanks :)

**Comment by HookedBehemoth** [comment]
Working on it but sadly at the end of the main NCA it fails :disappointed: 
Result is, that the game is on the main screen but won't boot because the install was incomplete.

**Comment by DarkMatterCore** [comment]
@HookedBehemoth What's the error you're getting? I'm not precisely familiar with content installation steps, but I have a few ideas that may (or may not) help.

**Comment by HookedBehemoth** [comment]
0x307202

**Comment by DarkMatterCore** [comment]
Thanks. Can you instruct me on the general code flow / IPC calls you're using to achieve content installation?

Also, arr you modifying the Program and/or CNMT NCAs in any way?

**Comment by HookedBehemoth** [comment]
Implemented and released with 1.2.0
