### ISSUE TITLE
Partially installed data error. Solution not in "closed issue"

### ISSUE THREAD

**Issue by WeetbixNMilk** [Huntereb/Awoo-Installer#82]
I'm having the issue where an install fails, says there is partially installed content and no data is present in "data management" -> "software" to remove. I'm using the latest Atmosphere Kosmos, is there a way to manually delete content or overwrite existing data?
Screenshots attached.
![awoo](https://user-images.githubusercontent.com/66398995/83708956-db079580-a660-11ea-9f5f-8562ef2c07e1.jpg)
![software](https://user-images.githubusercontent.com/66398995/83708957-dc38c280-a660-11ea-930e-114b972e4464.jpg)

**Comment by Huntereb** [comment]
Looks like bad signature patches. The warning telling you about removing partially installed contents is there just in case an install fails part way through. Your install didn't even start so you have no partially installed content.

I really need to make that error tell people to check their patches.

**Comment by koaie** [comment]
This also happens when installing non existing nsp files, (macos creates ._*.nsp when copying), can create utter confusion.
