### ISSUE TITLE
gdrive links via url do not work

### ISSUE THREAD

**Issue by donjonne** [Huntereb/Awoo-Installer#83]
first versions worked for me
lately no nsps can be installed via gdrive urls(last 2 versions)
can you verify code is same from previous versions?
error:
FAILED TO INSTALL GOOGLE DRIVE FILE!
PARTIALLY INSTALLED CONTENTS CAN BE REMOVED FROM THE SYSTEM SETTINGS APPLET
PERFORM REQUEST:  102: UNEXPECTED HTTP RESPONSE CODE WHEN RETRIEVING HEADER:  404

**Comment by donjonne** [comment]
I just uploaded a nsp to gdrive to test and it failed. the same nsp i uploaded is installable via awoo installer via sd card.

**Comment by AlessioScarlet** [comment]
same

**Comment by donjonne** [comment]
> same

i havent tried older versions because im afraid they may not work with updated sig patches.  if i have a chance ill test and let you know.
by the way game i tried was sm64 which was only like 20mb big

**Comment by Huntereb** [comment]
Are you using incognito? If so, stop using it and it will probably start working again. I've been told the latest version of curl does things involving console certs for ssl handshakes, and since you don't have those certs anymore...

**Comment by donjonne** [comment]
> Are you using incognito? If so, stop using it and it will probably start working again. I've been told the latest version of curl does things involving console certs for ssl handshakes, and since you don't have those certs anymore...

no  i  am not using incognito
can you upload sm64 to your gdrive and test for yourself?
i suggest sm64 because its only 20mb in size

**Comment by Huntereb** [comment]
I just installed something from gdrive a few days ago and it worked fine. You should try another file, or check and make sure you're typing the file ID properly.

**Comment by donjonne** [comment]
> I just installed something from gdrive a few days ago and it worked fine. You should try another file, or check and make sure you're typing the file ID properly.

welp there it goes
i typed it like a zillion times
typed the whole address when it didnt work
even tried to use a fileshare website
are we suppose to use "/" or something or just the file id letters and numbers?

**Comment by donjonne** [comment]
Update:
it worked
i figured my desktop reads the letter "l"(L) the same as "I"(i) and i was typing in it  incorrectly
very weird as i swear i tried both 

i guess we can close this thread down?
and how do i request for rar installation?
most websites include nsps rared unfortunately..

**Comment by donjonne** [comment]
working.  possibly typed incorrect google id or no network connection.

**Comment by donjonne** [comment]
working. possibly typed incorrect google id or no network connection.
