### ISSUE TITLE
USB installation failed or timed out

### ISSUE THREAD

**Issue by pitrako** [Huntereb/Awoo-Installer#85]
I'm getting "USB installation failed or timed out" errors randomly, It's that normal? (Awoo Installer 1.3.3 and ns-usbloader 2.2.1).

**Comment by donjonne** [comment]
i also had a failure but i was installig 3 game files at the same time.  i didnt bother retrying and installed via net.  via net it worked fine but obviously its slower

**Comment by mrjoehn** [comment]
same thing happened to me. Sometime I need to download NSP, XCI, NSZ files to see which one works. Any tips on avoiding this to happen? It seems that it is a similar issue with varying download speed 0 - 8 MB/s - 40 MB/s, but sometimes when it got stuck at 0, then it crashed and needed to be deleted manually from Data Management.

**Comment by donjonne** [comment]
> same thing happened to me. Sometime I need to download NSP, XCI, NSZ files to see which one works. Any tips on avoiding this to happen? It seems that it is a similar issue with varying download speed 0 - 8 MB/s - 40 MB/s, but sometimes when it got stuck at 0, then it crashed and needed to be deleted manually from Data Management.

so i tried it yesterday and it installed nsp fine a one 5gb file;  i did enable "gay mode";  you can enable it by editing the config file with wordpad.  i dont know if that did anything though.

**Comment by HookedBehemoth** [comment]
"gay mode" disables the Momiji Inubashiri figurine that maps to "Remove anime" in the options.
Except for maybe inefficient rendering this _shouldn't_ slow down installation.

**Comment by donjonne** [comment]
> "gay mode" disables the Momiji Inubashiri figurine that maps to "Remove anime" in the options.
> Except for maybe inefficient rendering this _shouldn't_ slow down installation.

i do remember hunter mentioning gaymode also allows rar file installation.  correct me if im wrong...

**Comment by HookedBehemoth** [comment]
nah
"gay mode" is exclusively for hiding the "awooImage"

**Comment by HookedBehemoth** [comment]
https://raw.githubusercontent.com/Huntereb/Awoo-Installer/master/romfs/images/awoos/5bbdbcf9a5625cd307c9e9bc360d78bd.png
https://raw.githubusercontent.com/Huntereb/Awoo-Installer/master/romfs/images/awoos/7d8a05cddfef6da4901b20d2698d5a71.png

**Comment by donjonne** [comment]
> https://raw.githubusercontent.com/Huntereb/Awoo-Installer/master/romfs/images/awoos/5bbdbcf9a5625cd307c9e9bc360d78bd.png
> https://raw.githubusercontent.com/Huntereb/Awoo-Installer/master/romfs/images/awoos/7d8a05cddfef6da4901b20d2698d5a71.png

so is rar file nsp installation even possible?

**Comment by Huntereb** [comment]
Tips to stop this from happening? Use Net installation. We warn people before even attempting their first USB installation that it isn't for everyone. There are an abundance of things that could interfere with this process. If it doesn't work for you, don't use it.

> so is rar file nsp installation even possible?
Sure it's possible, but it seems a lot faster and easier to perform extractions on another device before installation, right?

**Comment by donjonne** [comment]
> Sure it's possible, but it seems a lot faster and easier to perform extractions on another device before installation, right?


the thing is i like to install gdrive nsps but two things:
1.  most websites have nsps in rar format
2.  gdrive  installation has not worked for me as of lately because of a 404 error using latest version of awoo

it is very convinient to install via  gdrive as you dont have to download game, extract, boot up nsbuploader and than finally install.

**Comment by pitrako** [comment]
What means the error buffer:189 (I think that's the latest error It gave me).

**Comment by Huntereb** [comment]
Your USB port or cord is shit.

**Comment by pitrako** [comment]
USB port from PC can't be shit, usb cable maybe..., but I can connect hekate with the cable and do nand backup transfers to computer without errors.

**Comment by Huntereb** [comment]
Awoo Installer has a timeout for when transfers take too long to respond. If something is going too slow, you'll get the error you got.

**Comment by pitrako** [comment]
And what cable you suggest?, because the one I already have works for anything else (the only thing that fails sometimes is awoo).

**Comment by zeromaisum** [comment]
I changed from a usb 3.0 port to a usb 2.0 and it worked

**Comment by FlynnYork** [comment]
> 我将 USB 3.0 端口换成了 USB 2.0，一切正常



> I changed from a usb 3.0 port to a usb 2.0 and it worked

same issue.
