### ISSUE TITLE
White screen on 10.0.2

### ISSUE THREAD

**Issue by wolverine5pl** [Huntereb/Awoo-Installer#86]
When starting in on 10.0.2 on sx os i get white screen. any idea why?

**Comment by HookedBehemoth** [comment]
Could you take an image of the screen?
It's supposed to be cyan.

**Comment by wolverine5pl** [comment]
it is cyan. what should i do when screen is like that?

**Comment by HookedBehemoth** [comment]
Don't use SX OS!
