### ISSUE TITLE
custom themes for the application

### ISSUE THREAD

**Issue by Elionna** [Huntereb/Awoo-Installer#9]
It would be cool to be able to be able change the icon on the top left and the Momiji on the bottom right based on what we place inside the folder.

**Comment by Huntereb** [comment]
I could maybe make replacing the images a hidden feature if it detects the images exist in the main directory. Wouldn't be hard I guess.

**Comment by Huntereb** [comment]
As of https://github.com/Huntereb/Awoo-Installer/commit/86497d597281f63b0eb28652e6752a569affa122 this is a feature. You can put "awoo_main.png" and "awoo_inst.png" in /switch/Awoo-Installer/ and they will replace the standard images.

**Comment by Elionna** [comment]
thank you! just being able replace the images is exactly what I wanted
