### ISSUE TITLE
build error : error: 'RendererNoSound' is not a member

### ISSUE THREAD

**Issue by deejay87** [Huntereb/Awoo-Installer#90]
Hello
I try to build on ubuntu but have this error who is difficult to find, i have make Plutonium and move the content,  if someonne have an idea thanks :)

Awoo-Installer/source/main.cpp:14:34: error: 'RendererNoSound' is not a member of 'pu::ui::render::RendererInitOptions'
   14 |             RendererInitOptions::RendererNoSound, RendererHardwareFlags);

**Comment by Huntereb** [comment]
Might be new updates breaking stuff, I need to go in and mess with some stuff soon and try building with the latest everything again.

**Comment by deejay87** [comment]
Hello, i have change the libnx yesterday and  the build is finish without error (sorry don't remember to write this here)

**Comment by laurinneff** [comment]
since your issue is fixed, please close it

**Comment by Aliasim800** [comment]
Yes lol
