### ISSUE TITLE
Request: Keep last entered URL

### ISSUE THREAD

**Issue by runawaysheep** [Huntereb/Awoo-Installer#91]
I hope to keep last entered URL(at Install over internet).
It's always 'https://' when restart Awoo.
Usually the same IP and path are used and only file name is changed.
It's so hard to input full path in every time.

**Comment by Huntereb** [comment]
We already do this for the session at least. Wouldn't be hard to do I guess.

**Comment by Huntereb** [comment]
Added with https://github.com/Huntereb/Awoo-Installer/commit/b181a9183c82f3de0e7357615affa33f7062068a .
