### ISSUE TITLE
Update sigpatches again 

### ISSUE THREAD

**Issue by Aliasim800** [Huntereb/Awoo-Installer#92]
Just wanted to point this out again, the sigpatches are outdated and need to be updated, we can't have people with bad sigpatches and corrupted game messages.
You should also update the signature patches as soon as possible when a new hekate, atmosphere and firmware version is released, always keep the sigpatches up to date.

**Comment by Huntereb** [comment]
On it. :P

**Comment by Aliasim800** [comment]
Sorry for being annoying, shouldn't have put this up. You've got other things to do.
