### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by GioeleLaugelli** [Huntereb/Awoo-Installer#94]
Using latest release(1.3.3) on framework 10.1.0 some NSP/XCI/NSZ files aren't loading and switch ask me to turn airplane mode off.

How can i fix it?

**Comment by Aliasim800** [comment]
Could be a bad file that your trying to install that its telling you to turn aeroplane mode off. Try some different sources. The problem is likely not awoo installer, it could just be the files your installing.

**Comment by Huntereb** [comment]
Some games require an account check before starting. You'll have to find a dump with those checks patched out to get around this.
