### ISSUE TITLE
[Feature request] Add Spanish languaje

### ISSUE THREAD

**Issue by impeeza** [Huntereb/Awoo-Installer#95]
Hi can you please add the language Spanish to the repository.  I did translate the en.json file to sp.json file attached (as sp.zip).   I did try to create a  Pull request but I am not allowed.
[sp.zip](https://github.com/Huntereb/Awoo-Installer/files/4943105/sp.zip)

**Comment by impeeza** [comment]
Hi. Any idea how to propose this feature?

**Comment by Huntereb** [comment]
Thanks for the help!
